export const TEAM_NAMES = {
    MCO: "AS Monaco",
    RED: "Crvena Zvezda Belgrade",
    ZAL: "Žalgiris Kaunas",
    PAN: "Panathinaikos Athens",
    MAD: "Real Madrid",
    PRS: "Paris Basketball",
    PAM: "Valencia Basket",
    TEL: "Maccabi Tel Aviv",
    BAS: "Baskonia Vitoria-Gasteiz",
    ULK: "Fenerbahce Istanbul",
    HTA: "Hapoel Tel Aviv",
    OLY: "Olympiacos Piraeus",
    IST: "Anadolu Efes Istanbul",
    MUN: "Bayern Munich",
    DUB: "Dubai Basketball",
    MIL: "Emporio Armani Milan",
    BAR: "FC Barcelona",
    VIR: "Virtus Bologna",
    ASV: "ASVEL Villeurbanne",
    PAR: "Partizan Belgrade",
}


export const TEAM_ABB = {
    MCO: "ASM",
    RED: "CZV",
    ZAL: "ZAL",
    PAN: "PAO",
    MAD: "RMB",
    PRS: "PBB",
    PAM: "VAL",
    TEL: "MAC",
    BAS: "BSK",
    ULK: "FEN",
    HTA: "HTA",
    OLY: "OLY",
    IST: "EFS",
    MUN: "BAY",
    DUB: "DUB",
    MIL: "EA7",
    BAR: "BAR",
    VIR: "VIR",
    ASV: "ASV",
    PAR: "PAR",
}
