export const TEAM_NAMES = {
    MCO: "AS Monaco",
    RED: "Crvena Zvezda Belgrade",
    ZAL: "Žalgiris Kaunas",
    PAN: "Panathinaikos Athens",
    MAD: "Real Madrid",
    PRS: "Paris Basketball",
    PAM: "Valencia Basket",
    TEL: "Maccabi Tel Aviv",
    BAS: "Baskonia Vitoria-Gasteiz",
    ULK: "Fenerbahce Istanbul",
    HTA: "Hapoel Tel Aviv",
    OLY: "Olympiacos Piraeus",
    IST: "Anadolu Efes Istanbul",
    MUN: "Bayern Munich",
    DUB: "Dubai Basketball",
    MIL: "Emporio Armani Milan",
    BAR: "FC Barcelona",
    VIR: "Virtus Bologna",
    ASV: "ASVEL Villeurbanne",
    PAR: "Partizan Belgrade",
}